### ISSUE TITLE
Komentar

### ISSUE THREAD

**Issue by jO-Osko** [Kodermatic/SN-web1#2]
Drugače super

Samo pri preverjanju, ali se naj nadaljuje uporabljaš celoten niz, kar pomeni, da tudi izraz oblike `"[y"` prime. Načelome samo razdeliš zadeve na seznam, pa bo delalo to kar hočeš:
```python
while another_conversion in ["y", "yes"]:
    # loop
    pass
```

https://github.com/Kodermatic/SN-web1/blob/a371d1b1f3b5c383454c61139f75fb3b68c45b39/06_HW%20-%20Python%20(Conditions%20and%20loops)/06_Converter.py#L11

Si bomo pa sezname pogledali bolj natančno jutri.

**Comment by Kodermatic** [comment]
> Drugače super
> 
> Samo pri preverjanju, ali se naj nadaljuje uporabljaš celoten niz, kar pomeni, da tudi izraz oblike `"[y"` prime. Načelome samo razdeliš zadeve na seznam, pa bo delalo to kar hočeš:
> 
> ```python
> while another_conversion in ["y", "yes"]:
>     # loop
>     pass
> ```
> 
> https://github.com/Kodermatic/SN-web1/blob/a371d1b1f3b5c383454c61139f75fb3b68c45b39/06_HW%20-%20Python%20(Conditions%20and%20loops)/06_Converter.py#L11
> 
> Si bomo pa sezname pogledali bolj natančno jutri.

Hvala za komentar. Popravljeno.
